# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    import pandas as pd
    import plotly.graph_objects as go

    # Datos
    data = {
        'Año': [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023],
        'Extraccion': [None, None, None, 85664, 86577, 87842, 88840, 89351, 89548, 89944, 89804, 90629],
        'Concesionada': [64900, 63400, 65600, 66100, 66400, 66800, 67400, 67300, 67300, 67500, 67800, 68100]
    }
    df = pd.DataFrame(data)

    fig = go.Figure()

    # Línea Superior (Extracción)
    fig.add_trace(go.Scatter(
        x=df['Año'], y=df['Extraccion'],
        fill='tozeroy',
        mode='lines+markers',
        name='Extracción (M m³)',
        line=dict(color='#0066FF', width=3, shape='spline'), # shape='spline' suaviza la curva
        fillcolor='rgba(0,102,255,0.08)',
        marker=dict(size=6, color='#0066FF')
    ))

    # Línea Inferior (Concesionada)
    fig.add_trace(go.Scatter(
        x=df['Año'], y=df['Concesionada'],
        mode='lines+markers',
        name='Concesionada (km³ × 1000)',
        line=dict(color='#00C8B4', width=2, dash='dash', shape='spline'),
        marker=dict(size=6, color='#00C8B4')
    ))

    fig.update_layout(
        template="plotly_white",
        margin=dict(l=10, r=20, t=30, b=20),
        height=280,
        # Configuración de la Leyenda arriba y centrada
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.05,
            xanchor="center",
            x=0.5,
            font=dict(color="#4A5568")
        ),
        xaxis=dict(
            showgrid=False,
            tickmode='linear',
            tick0=2012,
            dtick=1,
            color="#94A3B8"
        ),
        yaxis=dict(
            gridcolor='#F0F5FF',
            color="#94A3B8",
            # Custom ticks para que se vea como en la imagen (e.g., 60k, 70k)
            tickvals=[60000, 70000, 80000, 90000],
            ticktext=['60k', '70k', '80k', '90k'],
            range=[55000, 95000] # El eje Y no empieza en 0
        ),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)'
    )
    fig.show()

    # ========================================================================

    from shiny import ui
    from shinywidgets import output_widget

    ui.row(
        ui.column(5,
            ui.h4("Tu Rutina Diaria", style="font-family: 'Space Grotesk', sans-serif; margin-bottom: 20px;"),
            ui.input_slider("ducha", "🚿 Ducha (minutos)", min=1, max=30, value=5),
            ui.input_slider("cafe", "☕ Tazas de café/día", min=0, max=10, value=2),
            ui.input_slider("lavadora", "🧺 Lavadora (veces/sem)", min=0, max=7, value=2),
            ui.input_slider("carne", "🥩 Porciones de carne/día", min=0.0, max=5.0, value=1.0, step=0.5),
            ui.input_slider("ropa", "👕 Prendas fast fashion/mes", min=0, max=15, value=2),
            ui.input_slider("digital", "📱 Horas en pantallas/día", min=0, max=16, value=4)
        ),
        ui.column(7,
            ui.output_ui("total_litros_ui"),
            output_widget("grafica_calculadora")
        )
    )
    #| context: server
    from shiny import render, reactive, ui
    from shinywidgets import render_widget
    import plotly.graph_objects as go
    import pandas as pd

    @reactive.Calc
    def calcular_desglose():
        return {
            "Pantallas": input.digital() * 0.8,
            "Ropa Nueva": input.ropa() * 90,
            "Lavadora": input.lavadora() * 11.42,
            "Café": input.cafe() * 140,
            "Ducha": input.ducha() * 10,
            "Carne de res": input.carne() * 2000
        }

    @render.ui
    def total_litros_ui():
        desglose = calcular_desglose()
        total = sum(desglose.values())
        return ui.HTML(f"""
            <div class="debt-total" style="margin-bottom: 20px;">
                <div class="label">Tu Deuda Hídrica Diaria</div>
                <div class="value">{int(total):,}</div>
                <div class="unit">litros / día estimados</div>
            </div>
        """)

    @render_widget
    def grafica_calculadora():
        desglose = calcular_desglose()
    
        df = pd.DataFrame({
            "Actividad": list(desglose.keys()),
            "Litros": list(desglose.values())
        }).sort_values(by="Litros", ascending=True)

        fig = go.Figure()
    
        fig.add_trace(go.Bar(
            x=df["Litros"],
            y=df["Actividad"],
            orientation='h',
            marker=dict(color="#0066FF"),
            text=df["Litros"].apply(lambda x: f"{int(x):,} L" if x > 0 else ""),
            textposition="auto"
        ))
    
        fig.add_vline(
            x=2360, 
            line_dash="dash", 
            line_color="#FF3B3B", 
            annotation_text="Promedio Nacional (2,360 L)",
            annotation_position="top left",
            annotation_font=dict(color="#FF3B3B", weight="bold")
        )

        fig.update_layout(
            template="plotly_white",
            height=380,
            margin=dict(l=0, r=20, t=40, b=0),
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            font=dict(family="DM Sans"),
            xaxis=dict(title="Litros diarios", gridcolor="#F0F5FF"),
            yaxis=dict(title="")
        )
        return fig

    # ========================================================================

    fig1 = go.Figure()
    labels_acceso = ["Red continua", "Llave pública", "Pipa de agua", "Acarreo/otros"]
    fig1.add_trace(go.Bar(y=labels_acceso, x=[57.4, 5.2, 8.3, 29.1], name="2016", orientation='h', marker=dict(color='rgba(184,212,255,0.9)')))
    fig1.add_trace(go.Bar(y=labels_acceso, x=[54.8, 6.1, 9.7, 29.4], name="2019", orientation='h', marker=dict(color='rgba(0,102,255,0.85)')))
    fig1.update_layout(barmode='group', template='plotly_white', margin=dict(l=0, r=10, t=30, b=0), height=240, legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5, font=dict(color="#4A5568")), paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(family="DM Sans"))
    fig1.update_xaxes(showgrid=True, gridcolor='#5c677d', ticksuffix="%")
    fig1.update_yaxes(showgrid=False, autorange="reversed")
    fig1.show()

    # ========================================================================

    fig2 = go.Figure()
    labels_genero = ["Mujeres sin red", "Mujeres con red", "Hombres sin red", "Hombres con red"]
    colors_genero = ["#FF3B3B", "#FF9A3B", "#2B8BFF", "#B8D4FF"]
    fig2.add_trace(go.Bar(y=labels_genero, x=[48.5, 38.2, 14.1, 10.3], orientation='h', marker=dict(color=colors_genero)))
    fig2.update_layout(template='plotly_white', margin=dict(l=0, r=10, t=0, b=0), height=180, showlegend=False, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(family="DM Sans"))
    fig2.update_xaxes(showgrid=True, gridcolor='#F0F5FF', ticksuffix="h")
    fig2.update_yaxes(showgrid=False, autorange="reversed")
    fig2.show()

    # ========================================================================

    cp_zonas = pd.DataFrame([
        {"CP_referencia": 10000, "Zona": "Valle de México - CDMX", "Estado": "Ciudad de México", "RHA": "XIII Valle de México", "Presion": 91.3, "Reserva": 12.5, "Anos": 1.8, "Poblacion": "9,200,000", "Estres": "Crítico", "Color": "#FF3B3B"},
        {"CP_referencia": 64000, "Zona": "Cuenca Río San Juan - NL", "Estado": "Nuevo León", "RHA": "IV Bravo-Conchos", "Presion": 88.2, "Reserva": 14.1, "Anos": 2.4, "Poblacion": "5,300,000", "Estres": "Crítico", "Color": "#FF3B3B"},
        {"CP_referencia": 44100, "Zona": "Cuenca Lago Chapala - JAL", "Estado": "Jalisco", "RHA": "VIII Lerma-Santiago", "Presion": 62.8, "Reserva": 34.0, "Anos": 8.5, "Poblacion": "5,200,000", "Estres": "Alta", "Color": "#FF9A3B"},
        {"CP_referencia": 21000, "Zona": "Cuenca Río Colorado - BC", "Estado": "Baja California", "RHA": "I Pen. Baja California", "Presion": 82.5, "Reserva": 11.8, "Anos": 2.1, "Poblacion": "1,900,000", "Estres": "Muy Alta", "Color": "#FF3B3B"},
        {"CP_referencia": 97000, "Zona": "Zona Karst Yucatán - Mérida", "Estado": "Yucatán", "RHA": "XII Península Yucatán", "Presion": 31.5, "Reserva": 65.0, "Anos": 22.0, "Poblacion": "1,100,000", "Estres": "Baja-Media", "Color": "#00C8B4"},
    ])

    #cp_zonas[["CP_referencia", "Zona", "Estado", "Presion", "Reserva", "Anos", "Estres"]]

    # ========================================================================

    fig_cp = go.Figure()

    fig_cp.add_trace(
        go.Scatter(
            x=cp_zonas["Presion"],
            y=cp_zonas["Reserva"],
            mode="markers+text",
            text=cp_zonas["Estado"],
            textposition="top center",
            # Estilizamos el texto de las burbujas
            textfont=dict(family="DM Sans", size=12, color="#4A5568", weight="bold"),
            marker=dict(
                size=18, # Burbujas un poquito más grandes
                color=cp_zonas["Color"], 
                line=dict(color="white", width=2), # Borde blanco más definido
                opacity=0.9
            ),
            customdata=cp_zonas[["Zona", "RHA", "Anos", "Estres"]],
            hovertemplate=(
                "<b>%{text}</b><br><br>"
                "Zona: %{customdata[0]}<br>"
                "Presión: <b>%{x}%</b><br>"
                "Reserva: <b>%{y}%</b><br>"
                "Años estimados: <b>%{customdata[2]}</b><br>"
                "Estrés: <b>%{customdata[3]}</b>"
                "<extra></extra>" # Esto quita el recuadro secundario feo del hover
            ),
        )
    )

    fig_cp.update_layout(
        template="plotly_white",
        margin=dict(l=20, r=40, t=30, b=20), # Más margen derecho para CDMX
        height=420, # Un poco más alta
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(family="DM Sans"),
        hoverlabel=dict(font_family="DM Sans", bgcolor="white") # Hover más limpio
    )

    # Ajustes clave en los ejes
    fig_cp.update_xaxes(
        title="Presión hídrica (%)", 
        title_font=dict(size=13, color="#94A3B8"),
        gridcolor="#E2EAFF", 
        zeroline=False,
        range=[25, 100] # Extendemos el límite hasta 100 para que quepa CDMX
    )
    fig_cp.update_yaxes(
        title="Reserva disponible (%)", 
        title_font=dict(size=13, color="#94A3B8"),
        gridcolor="#E2EAFF", 
        zeroline=False,
        range=[0, 80] # Extendemos hasta 80 para que Yucatán respire
    )

    fig_cp.show()

    # ========================================================================

    data_presion = {
        'Año': [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023],
        'Presion': [53.1, 51.9, 54.8, 55.4, 55.3, 55.3, 55.8, 55.7, 56.2, 56.4, 56.6, 55.9]
    }
    df_p = pd.DataFrame(data_presion)

    fig3 = go.Figure()
    fig3.add_trace(go.Scatter(x=df_p['Año'], y=df_p['Presion'], fill='tozeroy', mode='lines+markers', name='Grado de presión (%)', line=dict(color='#2B8BFF', width=3), fillcolor='rgba(43,139,255,0.1)', marker=dict(size=8, color='#0066FF')))
    fig3.add_trace(go.Scatter(x=df_p['Año'], y=[55]*len(df_p), mode='lines', name='Umbral crítico (55%)', line=dict(color='#FF3B3B', width=2, dash='dash')))

    fig3.update_layout(template="plotly_dark", margin=dict(l=0, r=0, t=20, b=0), height=200, legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1), paper_bgcolor='rgba(0, 0, 0, 0)', plot_bgcolor='rgba(0,0,0,0)', font=dict(family="DM Sans"))
    fig3.update_xaxes(showgrid=False, tickmode='linear', tick0=2012, dtick=1)
    fig3.update_yaxes(gridcolor='rgba(255,255,255,0.08)', range=[48, 60], ticksuffix="%")
    fig3.show()

    # ========================================================================



    return None


_static_assets = ["index_files","index_files\\libs\\quarto-html\\tippy.css","index_files\\libs\\quarto-html\\light-border.css","index_files\\libs\\quarto-html\\quarto-html-640605f58ae58ee79329c070719e555b.min.css","index_files\\libs\\quarto-html\\quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css","styles.css","index_files\\libs\\clipboard\\clipboard.min.js","index_files\\libs\\quarto-html\\tabby.min.js","index_files\\libs\\quarto-html\\popper.min.js","index_files\\libs\\quarto-html\\tippy.umd.min.js","index_files\\libs\\quarto-html\\anchor.min.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "index.html",
    server,
    static_assets=_static_assets,
)
